2020-09-06T00:13:59.2566595-03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-09-06T00:13:59.2751460-03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-09-06T00:13:59.2753163-03:00  [INF] Content root path: "F:\Projetos\Faculdade\Trabalho - middleware aal\middleware_autorization_authentication_auditing\middleware_autorization_authentication_auditing" (b5d60022)
2020-09-06T00:14:56.0747076-03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-09-06T00:14:56.0964469-03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-09-06T00:14:56.0967397-03:00  [INF] Content root path: "F:\Projetos\Faculdade\Trabalho - middleware aal\middleware_autorization_authentication_auditing\middleware_autorization_authentication_auditing" (b5d60022)
2020-09-06T00:14:59.3341873-03:00 80000006-0002-fe00-b63f-84710c7967bb [INF] Usuário  gabriel2mm efetuou login ás 06/09/2020 00:14 (1249124c)
2020-09-06T00:15:28.8417616-03:00 80000007-0002-fe00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at middleware.Controllers.RoleController..ctor(ILogger`1 logger, RoleManager`1 roleManager, UserManager`1 userManager) in F:\Projetos\Faculdade\Trabalho - middleware aal\middleware_autorization_authentication_auditing\middleware_autorization_authentication_auditing\Controllers\RoleController.cs:line 27
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-09-06T00:15:49.1575272-03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-09-06T00:15:49.1719420-03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-09-06T00:15:49.1721623-03:00  [INF] Content root path: "F:\Projetos\Faculdade\Trabalho - middleware aal\middleware_autorization_authentication_auditing\middleware_autorization_authentication_auditing" (b5d60022)
